### ISSUE TITLE
Prerequsites for MTLS.

### ISSUE THREAD

**Issue by rahul221192** [cloudfoundry-attic/cf-release#1256]
Hi team,

Its Regarding MLTS supports in cloudfoundry,
Can you please help me with prerequisites for MTLS?
Is credhub is a mandatory requirement for MTLS?

Thank in advance.
Rahul

**Comment by dsabeti** [comment]
Hi @rahul221192. We have an attempt to [document this process here](https://github.com/cloudfoundry/cf-release/blob/master/on-tls-certificates.md). It relies on [these `generate-*-certs` scripts](https://github.com/cloudfoundry/cf-release/tree/master/scripts).

As far as Credhub, it is not a requirement for enabling any MTLS.

**Comment by rahul221192** [comment]
Hi @dsabeti 
How at the apps level, mtls  works?
Do we need to add certificates in application too while pushing it on the cloud  foundry?

**Comment by dsabeti** [comment]
Yes, that sounds right.

**Comment by rahul221192** [comment]
If we are deploying CF on AWS and i want to enable mTLS on gorouter(termination at router only
) ,then which properties do be need to add/change  in cf manifest.
When we push the app with there own certificates how gorouter validate from CA authorities?
and how to check whether mTLS is happening or not?

**Comment by dsabeti** [comment]
Hey @rahul221192, I misunderstood your original question. It sounds like you want mutual TLS between the Gorouter and your application, is that right? If so, best to reach out to the routing team in the #routing channel of [Cloud Foundry Slack](https://cloudfoundry.slack.com), or open an issue on [the routing-release repo](https://github.com/cloudfoundry-incubator/routing-release) -- the team there should be able to help you out.

**Comment by rahul221192** [comment]
Hi @dsabeti sorry i think framed the question in wrong way. To be more precise , i was asking for mtls between the cloud foundry and third party apps which are not running on cloud foundry.
For them ,is credhub is mandatory requirement.

**Comment by dsabeti** [comment]
Hey @rahul221192, if you don't have control over the third-party apps, there's not way to do mutual TLS. In such a case, you'd need to use "normal" TLS -- your application should validate the certificate of the third-party app.

Even if you _do_ have control over the app that isn't hosted on CF, it may be possible to configure the apps to perform mutual TLS, but quite hard and not in a supported way. If you have more questions, you should reach out to the routing team, since doing this will require reconfiguring of your load balancers and gorouter, most likely.

**Comment by dsabeti** [comment]
Hi @rahul221192. I'm going to close this issue due to inactivity, but feel free to re-open this issue in the cf-deployment repo if you have more questions about it.
