### ISSUE TITLE
how to update update resolv.conf in Cloudfoundry VMS??

### ISSUE THREAD

**Issue by nsharmacovs** [cloudfoundry-attic/cf-release#1273]
When we deploy cloud foundry on AWS ,following entries are updated in resolv.conf
# cat /etc/resolv.conf 
nameserver x.x.x.x
nameserver x.x.x.x
search x.x.x.x

We would like to add "options rotate timeout:1 retries:1" in resolv.conf during VM creation process .

# cat /etc/resolv.conf 
options rotate timeout:1 retries:1
nameserver x.x.x.x
nameserver x.x.x.x
search x.x.x.x

What is the best way to achieve this ?

Regards,
Naresh Sharma

**Comment by dsabeti** [comment]
Hi @nsharmacovs. Changes to resolv.conf are made by BOSH rather than cf-release, so you'll have more success contacting the BOSH team. You can find them in their Slack channel (https://cloudfoundry.slack.com/messages/C02HPPYQ2) or opening an issue on https://github.com/cloudfoundry/bosh.

Also, cf-release is no longer a supported product. I'd advise you move to [cf-deployment](https://github.com/cloudfoundry/cf-deployment) as soon as possible.

**Comment by nsharmacovs** [comment]
Thanks for the reply .We are in process to move to CF-deployments .
